#!/bin/bash
CUDA_VISIBLE_DEVICES=0,1 python3 make_multilingual.py --config training_config.yaml > logs/output.log


# if [ ! -d "./output" ]; then
#     mkdir -p ./output
#     echo "mkdir output"
# fi

# if [ ! -d "./logs" ]; then
#     mkdir -p ./logs
#     echo "mkdir logs"
# fi

#  CUDA_VISIBLE_DEVICES=0  accelerate launch \
#  make_multilingual.py \
#  --config training_config.yaml  \
#  > logs/training.log &